### ISSUE TITLE
Exception Raised when Querying GSI

### ISSUE THREAD

**Issue by jasonlockporcelane** [numberoverzero/bloop#43] opened 2016-06-21 18:30 UTC
Hello, 
I'm not sure if this is a bug or i'm just doing something wrong, but when I try to query against a tables GSI a `ValidationException` is raised. 

Here is the full error message: ```botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the Query operation: Value provided in ExpressionAttributeNames unused in expressions: keys: {#n2}```. 

Here is a gist of the code i'm testing: https://gist.github.com/jasonlockporcelane/9c1baf819ef2b85b729d09f15d8a16aa

I'm also using DynamoDB local as described here: http://bloop.readthedocs.io/en/latest/user/patterns.html. 

Please let me know if you need any more info, I really appreciate the help!

**Comment by numberoverzero** [comment] 2016-06-21 19:01
I won't be able to dig into this fully for a few hours, sorry about that.  From a quick look, I'm guessing you've found a bug in either how requests are generated by the Filter, or how the renderer tracks reference names.

Can you use the following to debug the output?

```
# 0.9.12
query = engine.query(...).key(...)  # etc

# before iterating the results, but after building the query
iterator = query.all()

# DEBUG This is the json blob that will be sent to DynamoDB with each request
print(iterator.request)

# call that raises
result = list(iterator)

# ==========

# AFTER 0.9.12
query = engine.query(...).key(...)  # etc

# before iterating the results, but after building the query
iterator = query.build()

# DEBUG This is the json blob that will be sent to DynamoDB with each request
print(iterator._prepared_request)

# call that raises
result = list(iterator)
```


(Using an older commit since new commits aren't on pypi yet)
Here's the path for generating a Query request:

1. [Render `query.filter(...)`](https://github.com/numberoverzero/bloop/blob/ba33db30e6bd05128b3d946962ec093d1ee16144/bloop/filter.py#L200)
2. [Render `query.select(...)`](https://github.com/numberoverzero/bloop/blob/ba33db30e6bd05128b3d946962ec093d1ee16144/bloop/filter.py#L202)
3. [Dump rendered expressions into request](https://github.com/numberoverzero/bloop/blob/ba33db30e6bd05128b3d946962ec093d1ee16144/bloop/filter.py#L204)
4. [Render and dump `query.key(...)`](https://github.com/numberoverzero/bloop/blob/ba33db30e6bd05128b3d946962ec093d1ee16144/bloop/filter.py#L350)

Aside from a bug in the renderer (which is not entirely unlikely) I did notice that the above will cause the renderer's output to be updated into the request twice. That shouldn't matter, but..

**Comment by numberoverzero** [comment] 2016-06-21 19:12
Unrelated to this issue, but I notice you use filter twice which isn't having the intended effect - [each call replaces the previous value](https://github.com/numberoverzero/bloop/blob/ba33db30e6bd05128b3d946962ec093d1ee16144/bloop/filter.py#L272).

To use two filters, the conversion looks like this (with some contrived filter examples):

```
# Here, the second filter blows away the first :(
engine.query(Account).key(...) \
    .filter(Account.funds.between(5, 500)) \
    .filter(Account.reward_points >= 200)

# This time applying both filters instead of losing the first
engine.query(Account).key(...) \
    .filter(Account.funds.between(5, 500) &
            (Account.reward_points >= 200))

# Note the parens around the second filter so the & operator doesn't have precedence
```

At a minimum it means that the docs aren't clear, and it probably means I should revisit how bloop uses the builder pattern.  I think this style (express each filter individually, build the value up incrementally) is nicer, but there are a few drawbacks, especially when applied to other fields (and the behavior needs to be consistent across key, filter, select at least):

1. How do you clear all filters?  Could be just `None` but that doesn't fit the "filter always appends"  (or, maybe it's not possible to clear a filter, and don't include one in a base query)
2. Incremental building for `.key` makes the at-call validation much weaker.  Right now the key condition has to be valid for the model/index being queried, so it doesn't lie in wait until `.all()` to fail.  With incremental building, it would be hard to know if the current call's value was invalid, leaving the caller passing invalid data and seeing the failure somewhere else.
3. Same concern with clearing a key - is `None` allowed?  But this would also be invalid, if they don't replace it before `.all()`.

**Comment by jasonlockporcelane** [comment] 2016-06-21 19:58
It seems it might be related to use DynamoDB local, I switch to querying against DynamoDB directly and could't reproduce the exception. 

I just noticed that chaining filters overrides the first filter :) I'm porting SQLAlchemy to bloop and for some reason I thought you could build up filters in a similar fashion. Will need to pay closer attention to the docs. Thanks again for all the help!

**Comment by numberoverzero** [comment] 2016-06-21 20:07
I know local didn't support expressions when bloop first used them, but I'd be surprised if they're still not available.  Might not be a big feature request for them?

bloop has borrowed heavily from SQLALchemy, so the confusion is not unexpected.  I would prefer the syntax that feels natural for most users, and that may in fact be building up filters in stages.

How does sqlalchemy handle clearing filters?  Or is that not available, and once you add a filter it's part of the query?  I'd consider the argument that clearing isn't necessary (especially in the new syntax, which doesn't clone-on-call).  Does it offer a way to join consecutive filters as an OR instead of an AND?

**Comment by jasonlockporcelane** [comment] 2016-06-22 01:15
Going to do a little digging to see if the latest version of local supports expressions. The container i'm using seems to pull the [latests version](https://github.com/deangiberson/docker_aws_dynamodb_local/blob/master/Dockerfile#L17). Compared to what the DynamoDB docs [recommend](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html).

Here is the output when I debug the query request: 
```
{
    'ExpressionAttributeValues': {
        ':v1': {
            'S': '2016-08-08T23:59:00+00:00'
        },
        ':v3': {
            'S': '2016-08-08T00:00:00+00:00'
        }
    },
    'ConsistentRead': False,
    'ExpressionAttributeNames': {
        '#n2': 'shift_end',
        '#n0': 'shift_start'
    },
    'FilterExpression': '((#n0 <= :v1) AND (#n2 >= :v3))',
    'TableName': 'DEVDentists', 'Select': 'ALL_ATTRIBUTES'
}
``` 

I'm not to sure how sqlalchemy clears filters. I don't have a whole lot of experience with it; hence the migration to Bloop :) I also don't have a lot of context into what scenarios clearing filters would be necessary but for what it's worth, chaining filters together (`filter(...).filter(...)`) is nice syntactic sugar.

**Comment by numberoverzero** [comment] 2016-06-22 03:17
TODOs for me:
1. New issue for the filter chaining, and make some notes on options for keys and select.  Not certain that it'll change, but worth enumerating the options at least.
2. New issue for better Query/Scan documentation; at least its own section, like Working with Models.

---

To close this one out, I found [one other SO post](http://stackoverflow.com/questions/33847477/querying-a-global-secondary-index-in-dynamodb-local?rq=1) that was also struggling with a GSI query against local.

If you want to pursue this further with AWS regarding DynamoDB Local I don't mind tracking that forum thread here, but this doesn't look like an issue with bloop.  In addition to your validation against DynamoDB I ran some queries against a GSI with various filters and hash/hash+range combinations and couldn't reproduce the problem against live DynamoDB.

Closing, and again happy to re-open if there's any evidence that Dynamo Local works with a key+filter (using expressions) combination.

Thanks for the report!

**Closed by numberoverzero** 2016-06-22 03:17 UTC
